theme: jekyll-theme-minimal
title:  Vocabularies Consortium
description: An initiative dedicated to further the standardisation of metadata entities and associated vocabularies in cuneiform studies.
description: Minimal is a theme for GitHub Pages.
show_downloads: true
